name: "Deploy DBX Asset Bundle"
description: "Deploy DBX Asset Bundle to Databricks"
runs:
  using: "composite"
  steps:
    - uses: databricks/setup-cli@main

    - name: Validate Parameters
      run: bash ${GITHUB_ACTION_PATH}/validate.sh
      shell: bash
      env:
        AUTHENTICATION_TYPE: ${{ inputs.authentication-type }}
        DATABRICKS_TOKEN: ${{ inputs.databricks-token }}
        DATABRICKS_HOST: ${{ inputs.databricks-host }}
        ARM_CLIENT_ID: ${{ inputs.arm-client-id }}
        ARM_CLIENT_SECRET: ${{ inputs.arm-client-secret }}
    
    - name: Deploy Databricks Asset Bundle
      if: ${{ inputs.authentication-type == 'token' }}
      run: databricks bundle deploy
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      env:
        DATABRICKS_HOST: ${{ inputs.databricks-host }}
        DATABRICKS_BUNDLE_ENV: ${{ inputs.databricks-bundle-env }}
        DATABRICKS_TOKEN: ${{ inputs.databricks-token }}
    
    - name: Deploy Databricks Asset Bundle
      if: ${{ inputs.authentication-type == 'azure-managed-identity' }}
      run: databricks bundle deploy
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      env:
        DATABRICKS_HOST: ${{ inputs.databricks-host }}
        DATABRICKS_BUNDLE_ENV: ${{ inputs.databricks-bundle-env }}
        ARM_CLIENT_ID: ${{ inputs.arm-client-id }}
        ARM_USE_MSI: true
    - name: Validate Asset Bundle
      run: databricks bundle validate
      uses: databricks/setup-cli@main
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      env:
        DATABRICKS_HOST: ${{ inputs.databricks-host }}
        DATABRICKS_BUNDLE_ENV: ${{ inputs.databricks-bundle-env }}
        DATABRICKS_TOKEN: ${{ inputs.databricks-token }}